# -*- coding: utf-8 -*-
"""Problemseti2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1x6XI9yChR8nGvh9xmcRKO8D-0ST8Mx1W
"""

def kontrol(str):
    count1 = 1
    say = 0
    for ch in str:
        say += 1
        if ch == '@':
            say1 = say
            if (str[0:say-1].isidentifier()==False):
                break
            for ch1 in str[say:]:
                say += 1
                if ch1 == '.':
                    if (str[say1:say - 1].isalnum() == False):
                        break
                    for ch2 in str[say:say + 4]:
                        if ch2 == '.':
                            for num in str[say:]:
                                say += 1
                                count1 += 1
    if count1 != 1:
        return True
    else:
        return False


mailadresi = input('Mail adresinizi yazınız : ')
if (kontrol(mailadresi) == True):
    print('Mail adresiniz doğrudur')
else:
    print('Mail adresiniz yanlıştır')